version: "3.8"

services:
  api:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO}:${IMAGE_TAG}
    container_name: imgproc-api
    restart: unless-stopped

    # App listens on 3000 in the container
    ports:
      - "${HOST_HTTP_PORT:-3000}:3000"

    # Minimal env the container needs at runtime.
    # All other config is fetched inside the app from SSM + Secrets Manager.
    environment:
      NODE_ENV: production
      AWS_REGION: ${AWS_REGION}
      QUT_USERNAME: ${QUT_USERNAME}

    # Container should be stateless (no local volumes needed for A2)
    # volumes: []

    # Optional: simple healthcheck against the root path
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3